config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do 
    member do 
      get 'followings'
      get 'followers'
    end
    collection do
      get 'show_great_tweet'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  profile         :text
#  prefecture      :string
#  gender          :string
#  generation      :string
#

class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  # validates
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
    format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: { case_sensitive: false }
  validates :profile, length: { maximum: 400 }
  validates :gender, presence: true, on: :update
  validates :prefecture, presence: true, on: :update
  has_secure_password
  
  # relations
  
  has_many :microposts

  # 多数をフォローする
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed

  # 多数のフォロワーを持つ
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower

  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end
  
  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  # フォローしている人のつぶやきを取得する
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_variables, only: [:edit, :new, :update, :create, :followings, :followers, :show]
  before_action :ensure_login_user, only: [:edit, :update, :destroy]

  # GET /users/1
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc).page(params[:page]).per(7)
  end
  
  # GET /users/new
  def new
    @user = User.new
  end
  
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  
  # POST /users
  def create
    @user = User.new(user_params)
    flash[:success] = "Welcome to the Sample App!"
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  # PUT /users/1
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to @user, notice: 'User was successfully updated'
    else
      render 'edit'
    end
  end
  
  # DELETE /user/1
  def destroy
    @user = User.find(params[:id])

    # TODO write destroy
  end
  
  # GET /users/show_great_tweet
  def show_great_tweet
    gt = GreatTweet.all.sample
    redirect_to :back, notice: "【#{gt.name}】　〜#{gt.detail}〜" 
  end
  
  # POST  /users/1/followings followしているユーザ
  def followings
    @user = User.find(params[:id])
    @following_users = @user.following_users
  end

  # POST  /users/1/followers followされているユーザ  
  def followers
    @user =  User.find(params[:id])
    @follower_users = @user.follower_users
  end
  
  private
    # curreent_userとrequest idのuserが異なれば、redirectではじく
    def ensure_login_user
      user = User.find(params[:id])
      if user == current_user
        # do nothing
      else
        if logged_in?
          redirect_to current_user, notice: "You can't access the other's page"
        else
          redirect_to login_url, notice: "Please log in!" 
        end
      end
    end

    # strong parameters 
    def user_params
      params.require(:user).permit(:name, :email, :prefecture, :profile, :gender, :generation, :password, :password_confirmation)
    end
    
    # define common variables
    def set_variables
      @prefecture_hash = {
      "北海道" => "北海道",
    	"青森県" => "青森県",
    	"岩手県" => "岩手県",
    	"宮城県" => "宮城県",
    	"秋田県" => "秋田県",
    	"山形県" => "山形県",
    	"福島県" => "福島県",
    	"茨城県" => "茨城県",
    	"栃木県" => "栃木県",
    	"群馬県" => "群馬県",
    	"埼玉県" => "埼玉県",
    	"千葉県" => "千葉県",
    	"東京都" => "東京都",
    	"神奈川県" => "神奈川県",
    	"新潟県" => "新潟県",
    	"富山県" => "富山県",
    	"石川県" => "石川県",
    	"福井県" => "福井県",
    	"山梨県" => "山梨県",
    	"長野県" => "長野県",
    	"岐阜県" => "岐阜県",
    	"静岡県" => "静岡県",
    	"愛知県" => "愛知県",
    	"三重県" => "三重県",
    	"滋賀県" => "滋賀県",
    	"京都府" => "京都府",
    	"大阪府" => "大阪府",
    	"兵庫県" => "兵庫県",
    	"奈良県" => "奈良県",
    	"和歌山県" => "和歌山県",
    	"鳥取県" => "鳥取県",
    	"島根県" => "島根県",
    	"岡山県" => "岡山県",
    	"広島県" => "広島県",
    	"山口県" => "山口県",
    	"徳島県" => "徳島県",
    	"香川県" => "香川県",
    	"愛媛県" => "愛媛県",
    	"高知県" => "高知県",
    	"福岡県" => "福岡県",
    	"佐賀県" => "佐賀県",
    	"長崎県" => "長崎県",
    	"熊本県" => "熊本県",
    	"大分県" => "大分県",
    	"宮崎県" => "宮崎県",
    	"鹿児島県" => "鹿児島県",
    	"沖縄県" => "沖縄県"
      }

      @generation_hash = {
      "10代" => "10代",
    	"20代" => "20代",
    	"30代" => "30代",
    	"40代" => "40代",
    	"50代" => "50代",
    	"60代以降" => "60代以降",
      }
      
      @gender_hash = {"1" => '女', "2" => '男'}
      
    end
    

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.slim
= form_for current_user.following_relationships.build, :remote => true do |f|
  div = hidden_field_tag :followed_id, @user.id
  = f.submit "Follow", :class=>"btn btn-primary"

app/views/users/_follow_form.html.slim
- if current_user != @user
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_form.html.slim
.row
  .col-md-6.col-md-offset-3
    = form_for @user, :html => {class: "form-horizontal"} do |f|
      = render 'shared/error_messages', object: f.object
      .form-group
        = f.label :name
        = f.text_field :name, :class => "form-control"

      .form-group      
        = f.label :email
        = f.text_field :email, :class => "form-control"

      .form-group
        div
          = f.label :gender
        = f.label :gender, value: 1, class: "radio-inline" do
          = f.radio_button :gender, 1, class: "form-control", checked: true
          = '女'
        = f.label :gender, value: 2, class: "radio-inline" do
          = f.radio_button :gender, 2, class: "form-control"
          = '男'

      .form-group
        = f.label :prefecture
        = f.select :prefecture, @prefecture_hash, :selected => @user.prefecture, :class => "form-control"

      .form-group
        = f.label :generation
        = f.select :generation, @generation_hash, :selected => @user.generation, :class => "form-control"

      .form-group
        = f.label :profile
        = f.text_area :profile, :class => "form-control"

      .form-group
        = f.label :password
        = f.password_field :password, :class => 'form-control'

      .form-group  
        = f.label :password_confirmation, "Confirmation"
        = f.password_field :password_confirmation, :class => 'form-control'

      = f.submit "登録と更新", class: "btn btn-large btn-primary"

app/views/users/_unfollow.html.slim
= form_for current_user.following_relationships.find_by(followed_id: @user.id), :html => { :method=>:delete }, :remote=>true do |f|
  = f.submit "Unfollow", :class=>"btn"

app/views/users/_user_section.html.slim
section.user_info
  h1
    = gravatar_for @user
    = @user.name
  .user_details.table-responsive
    table.table.table-bordered.table-hover#user-table
      tbody
        tr 
          th 性別
          td = @gender_hash[@user.gender]
        tr 
          th 年代
          td = @user.generation
        tr 
          th 地域
          td = @user.prefecture
        tr 
          th 一言！
          td#user-show-profile = @user.profile
    p
      = link_to "Followerings", followings_user_path(@user), :class=>"btn btn-default"
    p
      = link_to "Followers", followers_user_path(@user), :class=>"btn btn-default"

app/views/users/edit.html.slim
h1 ユーザ情報の編集
= render 'form'

app/views/users/followers.html.slim
.row
  aside.col-md-4
    = render 'user_section'
  .col-md-8
    = render 'follow_form' if logged_in?
    h3
      = "#{@user.name} Followers (#{@follower_users.count})"
    .row
      - @follower_users.each do |follower|
        .col-md-3.follow-box
          .profile-img
            = gravatar_for follower
          .profiles
            ul 
              li = link_to follower.name, user_path(follower.id)
              li = @gender_hash[follower.gender]
              li = follower.generation
              li = follower.prefecture
              li = follower.profile

app/views/users/followings.html.slim
.row
  aside.col-md-4
    = render 'user_section'
  .col-md-8
    = render 'follow_form' if logged_in?
    h3 
      = "#{@user.name} Followings (#{@following_users.count})"
    .row
      - @following_users.each do |following|
        .col-md-3.follow-box
          .profile-img
            = gravatar_for following
          .profiles
            ul 
              li = link_to following.name, user_path(following.id)
              li = @gender_hash[following.gender]
              li = following.generation
              li = following.prefecture
              li = following.profile

app/views/users/new.html.slim
h1 Sign up

.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      = render 'shared/error_messages', object: f.object

      = f.label :name
      = f.text_field :name, :class => 'form-control'

      = f.label :email
      = f.email_field :email, :class => 'form-control'
      
      = f.label :password
      = f.password_field :password, :class => 'form-control'
      
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, :class => 'form-control'
      
      = f.submit "Create my account", :class => 'btn btn-primary'

app/views/users/show.html.slim
.row
  aside.col-md-4
    = render 'user_section'
  .col-md-8
    = render 'follow_form' if logged_in?

    = page_entries_info @microposts
    - if @user.microposts.any?
      h3 Microposts (#{@user.microposts.count})
      ol.microposts
        = render @microposts
    = paginate @microposts