config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do 
    member do 
      get 'followings'
      get 'followers'
    end
    collection do
      get 'show_great_tweet'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  

end

app/views/layouts/_footer.html.slim
.footer.navbar-fixed-bottom
  .container
    p
      | copyright yamamon

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "Microposts", root_path, :id => "logo"
    nav
      ul.nav.navbar-nav.navbar-right
        li = link_to "Home", root_path
        li = link_to "Help", '#'
        - if logged_in?
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              | Users
              b.caret
            ul.dropdown-menu
              li = link_to "Your Followers",  followers_user_path(current_user)
              li = link_to "Your Followings", followings_user_path(current_user)
              li.divider
              li = link_to "All Users", "#"
          li.dropdown 
            a.dropdown-toggle data-toggle="dropdown" href="#"
              | Account
              b.caret
            ul.dropdown-menu
              li = link_to "Profile", current_user
              li = link_to "Settings", edit_user_path(current_user)
              li = link_to "Playing", show_great_tweet_users_path
              li.divider
              li = link_to "Log out", logout_path, method: "delete" 
        - else
          li = link_to "Log in", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Microposts
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render 'layouts/header'
    #main
      .container
        - flash.each do |message_type, message|
          div[class="alert alert-info alert-#{message_type}"]
            = message
        = yield
      = render 'layouts/footer'